# main settings configuration for the LunarLander game
GAME_WIDTH = 1024
GAME_HEIGHT = 800
GAME_TITLE = "Lunar Lander"
GAME_LINE_POINT_DISTRIBUTION = 50
GAME_SHAPE_FRICTION = 0.5
GAME_LUNAR_GRAVITY_CONSTANT = 0.005
GAME_LUNAR_VELOCITY = 2
GAME_LUNAR_START_FUEL = 2500
GAME_SPEED_FACTOR = 50
GAME_LUNAR_FUEL_REDUCE = 1
GAME_LUNAR_FUEL_REDUCE_FACTOR = 4
GAME_LUNAR_LANDING_TOLERANCE = 10
GAME_LUNAR_BONUS_FACTOR = 50
GAME_BACKGROUND_STARS_AMOUNT = 20
GAME_BACKGROUND_STARS_BASE_RADIUS = 0.5