# main settings configuration for the LunarLander game
GAME_WIDTH = 1024
GAME_HEIGHT = 800
GAME_TITLE = "Lunar Lander"
GAME_LINE_POINT_DISTRIBUTION = 50
GAME_SHAPE_FRICTION = 0.5
GAME_LUNAR_GRAVITY_CONSTANT = 0.005
GAME_LUNAR_VELOCITY = 2